language: node_js
sudo: required
before_script:
- npm install -g bower polylint web-component-tester
- bower install
- polylint
env:
  global:
  - secure: RFYa8xQdlqjBhJG2OUDhskG/c9xdU7U1sCPyvKckWFkaLrxQnkN3OFASJGOWPLlwwoErpU5A7nuHanF911TSGMlrBSqRSFpr/t3gH8mrRJ8bzxASXf/eaJ3PfWyh9jDLJ0JCAr+eONmltSfndvmUYU1SdRpuW+kuAnmaJERIJTQBqZ2fJZ2J94c03tcVOClhe33Y4gMxk0GEyzYq2a1UHEmwFyco0v/BaedP/6bx1UWNF5HePnztnc3xPrVdKE5mX2wRdOy0nXNKIpidilXEMx4GjTi7shwBQNvV1WgD+lFV/tx2SyvevSZFtN1BWzZR4wLFy845FaylIjWO8NfI9/b6y1HHGDLb+0scu2M0FuUKYgQmzyZ4bEGb1iz0+7QN+3l3CePidUD3u+dQbkfoY2qoDV1GsY8ImHBXlxe9qUmz95lNLo2jPbI4D/8mXMgGbvegs+4/YtsbqwigyMH4QJRhWvb5VotRa9wHrm5XRlh6/vGTfOj5dC7q6anHSEibYMVGB5UEM4QhW3NLmVz1IfgUVHlaoDyfhKK3wfekNoSOBT4Wf/aW9MnrMpxlJNiqblmNPsfq0kcTs4KbzzDijCXL0bIlRH/bRnP9ko7IKO2woh6MPibXuPT+s+ElimJohfGeg77+DXDCNalYGdaqZrhxShZEKPtwKXbsVDl/mHk=
  - secure: 07gkfZTmALf9vBDIQIvXqfslyKlARofiPXFbFKsgs5pbCUrPdfPimpCgIwvukD3FFsdiIXqvBrya5rv6qZG6z1i4uhMQgjRvGIgV8OcxTeIPUdR1dIWURmKS6Xqb8+gdkfO0CUuFu9LfP6whF/9MmaHT1Iai8lFdrUknk2r7bREHfr3rXLIjcJ7dmBuKBDu5mTAC8oISD9j5zywBxk5l/WFb6kvf04vqpwEiVdXZCOVo+kkkgZYm0/BK+ObI5YTdpk5+76soO/q1sUA/kwyK73jh5efi/1KYdPa1SOUT6ehHE3zKD/SQgBkWzpR/HVvlle5ar9bUkSm9AqoyUCoSmRPzx1iwDdG5hvpSFgrEojNKet6EaCSzTyEVO6O+EGVf4Nld8XL2mMq54N8TTMRwCPD3DCEoThiLYnpIB3z9lUUroyyKoxhGw3vJoilMKf6dgDR8TPJtRMPGnQxaipm1KvVYzUBpCYWRtnsUhnATsYJzHCq+rB3r/7CDMF0ipeySx7BvtjHOnoYiA++p1FsZxU5S2bUXpE03sPj7i/nVwbW2w9LJt2g1fiRpMX9ADDqj9PRcKqWhY6agpfRAVNnwls4zwK0RtGV9a56ktDVs4DuRstGtNrdsb8IIzWbD50He7hEpVOd95afCHXhchvoYASYUZWlw9EAa0NstO/N1kqM=
node_js: stable
addons:
  firefox: '46.0'
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
  sauce_connect: true
script:
- xvfb-run wct
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct -s 'default'; fi
dist: trusty
